version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "${PORT:-15433}:${PORT:-15433}"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - API_BASE_URL=http://localhost:${PORT:-15433}
    command: poetry run uvicorn copilot_more.server:app --port ${PORT:-15433} --host 0.0.0.0 --reload
